#
# Pour ubuntu 14.04
#

- name: Installation de x2go
  hosts: localhost
  remote_user: root
  tasks:
    - name: Installation de python-software-properties
      apt: name=python-software-properties state=latest
    - name: Ajout du ppa x2go
      apt_repository: repo='ppa:x2go/stable' state=present
    - name: Linux Update/upgrade
      apt: upgrade=dist
    - name: Installation de x2go
      apt: name=x2goserver state=latest
      apt: name=x2goserver-xsession state=latest
      apt: name=xfce4 state=latest


- name: Installation de la configurations générales
  hosts: localhost
  remote_user: root
  tasks:
    - name: Installation de ntp
      apt: name=ntp state=latest
    - name: Installation de Gedit
      apt: name=gedit state=latest
    #- name: Installation de Firefox
    #  apt: name=firefox state=latest
    - name: Installation de unzip
      apt: name=unzip state=latest
    #- name: Installation de Thunderbird
    #  apt: name=thunderbird state=latest
    #- name: Installation de GAdminProFTPd
    #  apt: name=gadmin-proftpd state=latest
    #- name: Installation de clamav
    #  apt: name=clamav state=latest
    - name: Installation de gdebi
      apt: name=gdebi state=latest
    - name: Installation de erlang
      apt: name=erlang state=latest
    - name: Installation de doxygen
      apt: name=doxygen state=latest
    #- name: Installation de mysql workbench
    #  apt: name=mysql-workbench state=latest
    - name: Serveur en Français
      apt: name=language-pack-fr state=latest
      apt: name=language-pack-fr-base state=latest

    - name: gestion utilisateur
      user: name=django comment="django" password="django" uid=1040 group=root

- name: Installation du serveur web
  hosts: localhost
  remote_user: root
  tasks: 
    - name: Installation de Git
      apt: name=git state=latest

    - name: Installation make et cmake
      apt: name=make state=latest
      apt: name=cmake state=latest

    - name: Installation de python
      apt: name=python state=latest
      apt: name=python-pip state=latest
      apt: name=python-dev state=latest
      apt: name=libpq-dev state=latest
      apt: name=build-dep state=latest
      apt: name=python-psycopg2 state=latest
      apt: name=python-lxml state=latest
      apt: name=python-cffi state=latest
      apt: name=build-essential state=latest

    - name: Installation de python3
      apt: name=python3 state=latest
      apt: name=python3-dev state=latest
      apt: name=python3-pip state=latest
      apt: name=python3-cffi state=latest

    - name: Installation de postgresql
      apt: name=postgresql state=latest
      apt: name=postgresql-client state=latest
      apt: name=postgresql-client-common state=latest
      apt: name=postgresql-contrib state=latest
      apt: name=phppgadmin state=latest
      apt: name=pgadmin3 state=latest

    #- pip: name=python-psycopg2
      #template: src=/mytemplates/foo.j2 dest=/etc/apache2/conf.d/phppgadmin owner=root group=root mode=0777 # fichier de conf allow from all(decommenté)
    #- postgresql_user: db=score name=django password=antoine priv=ALL
    - service: name=apache2 state=started enabled=yes
    
    - name: Installation de MySQL
      apt: name=mysql-server state=latest
      apt: name=libmysqlclient-dev state=latest

    - pip: name=MYSQL-python 
    #- mysql_user: name=antoine password=antoine priv=*.*:ALL state=present
    #- mysql_db: name=score state=present


    - name: Installation de supervisor
      apt: name=supervisor update_cache=yes state=latest

    - name: Installation de Apache et php
      apt: name=apache2 update_cache=yes state=latest
      apt: name=apache2-utils update_cache=yes state=latest
      apt: name=php state=latest
      apt: name=libapache2-mod-php state=latest
      apt: name=libapache2-mod-wsgi state=latest
      apt: name=libapache2-mod-wsgi-py3 state=latest
      apt: name=php-pgsql state=latest
      apt: name=phpmyadmin state=latest

    #- name: Installation de nginx
    #  apt: name=nginx  state=latest

    - name: Installation de Lilypond
      apt: name=lilypond state=latest

    - name: Installation de rabbitmqserver
      apt: name=rabbitmq-server state=latest
    - rabbitmq_plugin: names=rabbitmq_management state=enabled
    - service: name=rabbitmq-server state=reloaded

    - name: Installation de gitlab
      apt: name=curl state=latest
      apt: name=openssh-server state=latest
      apt: name=ca-certificates state=latest
      apt: name=postfix state=latest
    - get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh dest=/home/gitlab.sh mode=0777
    #- shell: gitlab.sh chdir=/home/
    #- apt: name=gitlab-ce state=latest
    #- command: gitlab-ctl reconfigure

    - name: Installation de mantis (bugtracker)
      apt: name=curl state=latest
    #- unarchive: src=https://github.com/mantisbt/mantisbt/archive/release-1.3.0-rc.2.zip dest=/var/www/html/ copy=no

    - name: Installation de Django
      pip: name=django 
      pip: name=gunicorn 

    - name: Installation de nodejs
      apt: name=nodejs state=latest
      apt: name=npm state=latest

    - name: Installation de redis + redis commander
      apt: name=redis-server state=latest
    #- command: npm install -g redis-commander
    # pour ubuntu 14.04
    #- command: ln -s /usr/bin/nodejs /usr/bin/node 
    #- file: path=/usr/bin/nodejs src=/usr/bin/node state=link force=no
    #- command: redis-commander --redis-host 192.168.33.15


    - get_url: url=https://raw.githubusercontent.com/ajenti/ajenti/master/scripts/install.sh dest=/home/ajenti.sh mode=0777
    - shell: bash /home/ajenti.sh

    - name: Installation de ajenti (panel admin)
      pip: name=ajenti-panel state=present
      pip: name=ajenti.plugin.dashboard state=present
      pip: name=ajenti.plugin.settings state=present
      pip: name=ajenti.plugin.pluins state=present
      pip: name=ajenti.plugin.filemanager state=present
      pip: name=ajenti.plugin.notepad state=present
      pip: name=ajenti.plugin.packages state=present
      pip: name=ajenti.plugin.services state=present
      pip: name=ajenti.plugin.terminal state=present

    - name: Installation libgit2 et pygit2
      unarchive: src=https://github.com/libgit2/libgit2/archive/v0.24.1.tar.gz dest=/home/ copy=no 
    - command: cmake . chdir=/home/libgit2-0.24.1/
    - make: chdir=/home/libgit2-0.24.1/
    - make: chdir=/home/libgit2-0.24.1/ target=install
      become: yes
    - pip: name=pygit2
    - command: ldconfig

    - name: Installation piwik
      pip: name=django state=present
    - unarchive: src=https://builds.piwik.org/piwik.zip dest=/var/www/html/ copy=no mode=0777

    - name: Installation de sémaphore (CI ansible)
      pip: name=django state=present
    - get_url: url=https://github.com/ansible-semaphore/semaphore/releases/download/v2.0.4/semaphore_linux_amd64 dest=/usr/bin/semaphore mode=0777
      #- command: semaphore -setup chdir=/usr/bin/semaphore/
      

    - name: Création virtual host
      file: path=/etc/score/ state=directory mode=0777
      file: path=/etc/piwik/ state=directory mode=0777
      file: path=/etc/asset/ state=directory mode=0777
      file: path=/etc/gitlab/ state=directory mode=0777
      file: path=/etc/pgsql/ state=directory mode=0777
      

    - name: La maison des partitions | Cloning repos + submodules
      git: repo=https://banco29510:antoine29510@bitbucket.org/banco29510/score_c9.git
           dest=/var/www/html/django
           accept_hostkey=yes
           force=yes
           recursive=no   
    #- pip: requirements=/var/www/html/django/requirements.txt
    #- django_manage: command=migrate app_path=/var/www/html/django
    #- django_manage: command="createsuperuser --noinput --username=admin --email=admin@example.com" app_path=/var/www/html/django
    #- django_manage: command="changepassword --noinput admin admin" app_path=/var/www/html/django
    #- django_manage: command=createcachetable app_path=/var/www/html/django
    #- command: doxygen doxygen -g /var/www/html/django/doxyfile

  handlers:
    - name: restart apache
      service: name=httpd state=restarted