
- name: Installation de x2go
  hosts: localhost
  become: yes
  tasks:
    - name: Installation de python-software-properties
      apt: name=python-software-properties state=latest
    - name: Ajout du ppa x2go
      apt_repository: repo='ppa:x2go/stable' state=present
    - name: Linux Update/upgrade
      apt: upgrade=dist
    - name: Installation de x2go
      apt: name=x2goserver state=latest
      apt: name=x2goserver-xsession state=latest
      apt: name=xfce4 state=latest